// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPuqOON8kRTdJvehbajHKcJxOkp1bzbjE',
    appId: '1:314602030254:web:521f86b4eb8bad79c3593f',
    messagingSenderId: '314602030254',
    projectId: 'authconn-33379',
    authDomain: 'authconn-33379.firebaseapp.com',
    storageBucket: 'authconn-33379.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjC4rUO5GYjtJVTMWojxFXgAk7KObX-Is',
    appId: '1:314602030254:android:519b9a63cb72a5c4c3593f',
    messagingSenderId: '314602030254',
    projectId: 'authconn-33379',
    storageBucket: 'authconn-33379.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp7vHXRIbJfIYdVopP-OGIPWgETiveJqA',
    appId: '1:314602030254:ios:8a62f5fa4006ebecc3593f',
    messagingSenderId: '314602030254',
    projectId: 'authconn-33379',
    storageBucket: 'authconn-33379.appspot.com',
    iosBundleId: 'com.example.dbauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp7vHXRIbJfIYdVopP-OGIPWgETiveJqA',
    appId: '1:314602030254:ios:44ddf86f5a9aafa1c3593f',
    messagingSenderId: '314602030254',
    projectId: 'authconn-33379',
    storageBucket: 'authconn-33379.appspot.com',
    iosBundleId: 'com.example.dbauth.RunnerTests',
  );
}
